import React from 'react';
import { MdDownload } from 'react-icons/md';

interface SmartReportButtonProps {
  filename: string;
  title: string;
  sections: Array<{ heading: string; content: string[] }>;
}

const SmartReportButton: React.FC<SmartReportButtonProps> = ({ filename, title, sections }) => {
  const downloadReport = () => {
    const body = `<!doctype html><html><head><meta charset="utf-8" /><title>${title}</title><style>body{font-family:Arial,sans-serif;padding:32px;color:#16321f}h1{color:#166534}h2{margin-top:24px;color:#14532d}li{margin:8px 0} .meta{color:#4b5563;margin-bottom:20px}</style></head><body><h1>${title}</h1><div class="meta">Generated by KrishiSarthi on ${new Date().toLocaleString()}</div>${sections.map(section => `<h2>${section.heading}</h2><ul>${section.content.map(item => `<li>${item}</li>`).join('')}</ul>`).join('')}</body></html>`;
    const blob = new Blob([body], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename.endsWith('.html') ? filename : `${filename}.html`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <button
      onClick={downloadReport}
      className="inline-flex items-center gap-2 rounded-lg bg-primary-600 px-4 py-2 text-sm font-semibold text-white hover:bg-primary-700 transition-colors"
    >
      <MdDownload className="text-lg" />
      Download smart report
    </button>
  );
};

export default SmartReportButton;
